sudo: required

services:
  - docker

before_install:
  - docker build -t kaleido01/docker-complex-container -f ./client/Dockerfile.dev ./client

# テストしたい数だけbefore_installとscriptを組み合わせればok
script:
  - docker run -e CI=true kaleido01/docker-complex-container yarn test -- --coverage

after_success:
  - docker build -t kaleido01/client ./client
  - docker build -t kaleido01/nginx ./nginx
  - docker build -t kaleido01/server ./server
  - docker build -t kaleido01/worker ./worker
  #dockerにログイン
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #これらのイメージをdocker hubにpush
  - docker push kaleido01/client
  - docker push kaleido01/nginx
  - docker push kaleido01/server
  - docker push kaleido01/worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-us-east-2-145160279582
  bucket_pass: docker-complex
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
